[project]
name = "proj-jailbreak-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerator>=2025.9.5",
    "autoawq>=0.2.9",
    "fastchat>=0.1.0",
    "jupyterlab>=4.4.10",
    "matplotlib>=3.10.7",
    "nltk>=3.9.2",
    "openai>=2.7.2",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "tenacity>=9.1.2",
    "transformers>=4.57.1",
]
